version: 2
jobs:
  build:
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-{{ checksum "gradle/dependency-locks/compileClasspath.lockfile" }}-{{ checksum "gradle/dependency-locks/testCompileClasspath.lockfile" }}
            - v1-gradle-
      - run: ./gradlew check --info
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      - save_cache:
          paths:
            - "~/.gradle"
            - "~/.m2"
          key: v1-gradle-{{ checksum "gradle/dependency-locks/compileClasspath.lockfile" }}-{{ checksum "gradle/dependency-locks/testCompileClasspath.lockfile" }}

      - deploy:
          name: Release to kamatama41/maven-repository and Gradle plugin portal
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              echo "gradle.publish.key=${GRADLE_PUBLISH_KEY}" >> ~/.gradle/gradle.properties
              echo "gradle.publish.secret=${GRADLE_PUBLISH_SECRET}" >> ~/.gradle/gradle.properties
              git config --global user.email "shiketaudonko41@gmail.com"
              git config --global user.name "kamatama41"
              git checkout master
              git reset --hard origin/master
              ./gradlew release -Prelease.useAutomaticVersion=true
            fi
